### PR TITLE
This commit adds the backend functionality of the edit account function for a particular wire account and the implementation of the background image for the wire account.

### PR DESCRIPTION
**Pull request by PYRET1C**

### CODE REVIEW

**Comment by csoler** [comment]
Why is this PR changing entire files at once (e.g. p3wire.cc), whereas the actual changes only concern small sections of these files? If possible, could you plz remake the PR so that the changes are limited to the relevant parts?

**Comment by defnax** [comment]
i think you need do it manually create a new branch from your master and copy manually changes to your new branch but normally its easier when master is update then can create a new clean branch and copy your changes  manually to "rswireaccountedit" example

i did this way when my branch has bad commits (github desktop)
image
image
image
image

normaly i create from up to date a master a branch and i start edit with fresh branch then i commit the changes to new branch,
i do not do more merge branch stuff maybe that will look your pr ugly

**Comment by defnax** [comment]
i has created fresh and clean pr from your changes
https://github.com/RetroShare/libretroshare/pull/104

**Comment by PYRET1C** [comment]
okay i will make the new pr with new branch containing changes

**Comment by defnax** [comment]
@PYRET1C  when you a making a new pr? i

**Comment by PYRET1C** [comment]
tonight or tomorrow morning, i have done the changes, i only need to test the branch.

**Comment by defnax** [comment]
any news when comes the clean pr here?

**Comment by PYRET1C** [comment]
https://github.com/RetroShare/RetroShare/pull/2746
https://github.com/RetroShare/libretroshare/pull/105
I made new PR but they have a issue. they do not compile. the error it says is this:

D:/new/RetroShare-msys2/msys2/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: temp/obj/CustomFrame.o: in function `CustomFrame::setPixmap(QPixmap)':
D:/new/RetroShare/retroshare-gui/src/gui/TheWire/CustomFrame.cpp:19: multiple definition of `CustomFrame::setPixmap(QPixmap)'; temp/obj/CustomFrame.o:D:/new/RetroShare/retroshare-gui/src/gui/TheWire/CustomFrame.cpp:19: first defined here

It happens for all the functions in the CustomFrame.cpp, i tried solving it. I do not know what is causing it. There is only one definition of each function according to me.

**Comment by defnax** [comment]
when get time i can test it, i has thinked you solved it always.
but what i see you forget on the .pro to add the source and header file, it missed on the gui pr

**Comment by defnax** [comment]
@PYRET1C you can close this one

**Comment by PYRET1C** [comment]
done

**Comment by PYRET1C** [comment]
done

**Pull request closed without merging**
